### ISSUE TITLE
Farmer Akma Mission Still Broken

### ISSUE THREAD

**Issue by ChildServices** [DrSuperGood/SC2-UA3#12]
Title speaks for itself, however I've noticed that it doesn't happen as often, if at all, with higher player counts (above 7-8 or so)

**Comment by willmon8** [comment]
This was listed in previously closed "Issue #8", but UA3 players were reporting having no such problem and I wasn't able to duplicate it in public games.  It didn't occur to me to re-try the 4 man games where I first experienced the bug.  Unsure why this would be effected by number of players.  Perhaps REDCELL5 can figure it out.

**Comment by willmon8** [comment]
Tested tonight three times in solo gameplay.  First time, nothing happened after BMDDs failed - game stagnated indefinitely.  Second time, Chapter 1 started and Akma mission request was displayed after BMDDs failed.  Third time, worked again as it should after BMDD failure.  Unsure what triggers this.

**Comment by UAAnubis** [comment]
Please take a look at PR #16 and let me know what you think.

**Comment by UAAnubis** [comment]
There also seems to be an off-by-one error in completion checks for Akma Loop, which causes the mission to be completed with one less silo than intended.

**Comment by DrSuperGood** [comment]
> Please take a look at PR #16 and let me know what you think.

That solution looks iffy...

> There also seems to be an off-by-one error in completion checks for Akma Loop, which causes the mission to be completed with one less silo than intended.

The end conditional test seemed to have been designed for an index 0 start and not index 1 start.

I could swear that mission worked perfectly when I stopped development. I am guessing one of the previous pull requests must have broken it, sigh...

I will be publishing a fixed version to Blizzard servers shortly. Please test and let me know if it is really fixed so this can be closed.

**Comment by DrSuperGood** [comment]
So is this solved or is it not? It is hard to manage a project if people do not provide feedback...

**Comment by UAAnubis** [comment]
Apologies. I did not have the chance to test until yesterday. It seems to be working correctly now.

Thanks for your efforts.
